name: cd-develop

on:
  push:
    branches:
      - develop

jobs:
  dev-dep-job:
    environment: "development"
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Job
        run: echo "Deployed on Render"
      - name: Message to Render
        run: curl -X POST ${{ secrets.RENDER_CALLBACK_URL_DEVELOP }}
