name: cd-main

on:
  push:
    branches:
      - main

jobs:
  main-dep-job:
    environment: "main"
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Job
        run: echo "Deployed on Render"
      - name: Message to Render
        run: curl -X POST ${{ secrets.RENDER_CALLBACK_URL_MAIN }}
